blueprint:
  name: Frigate Notifications
  domain: automation
  input:
    camera:
      name: Camera
      selector:
        entity:
          filter:
            integration: frigate
            domain: camera            
    notify:
      name: Notification Target
      selector:
        entity:
          multiple: true
          filter:
            domain: notify
    conditions:
      name: Notification Condition(s)
      default: []
      selector:
        condition:
    mqtt:
      name: MQTT Path
      default: 'frigate/reviews'
      selector:
        text: 
    review_type:
      name: Review Type
      default: 'Both'
      selector:
        select:
          options:
            - label: Alerts and Detections
              value: all
            - label: Alerts
              value: alerts
            - label: Detections
              detections: detections

variables:
  camera_entity: !input camera
  camera_name: "{{ camera_entity | replace ('camera.', '')}}"
      
triggers:
  - trigger: mqtt
    topic: !input mqtt

conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.after.camera == camera_name }}"


actions:
  - variables:
      review_id: "{{ trigger.payload_json.after.id }}"
      update_type: "{{ trigger.payload_json.type }}"  
  - action: notify.mobile_app
    target: 
      entity_id: !input notify
    data:
      title: Frigate
      message: "{{ 'Camera ' + camera_name + ' has been triggered.' }}"
      data:
        image: >
             {% if update_type != 'end' %}
                  https://hass.arnie580.co.uk/api/frigate/notifications/{{ review_id }}/review_preview.gif
             {% else %}
                  https://hass.arnie580.co.uk/api/frigate/notifications/{{ review_id }}/thumbnail.jpg?format=android
             {% endif %}     
        tag: "{{ review_id }}"
