blueprint:
  name: Frigate Notifications
  domain: automation
  input:
    camera:
      name: Camera
      selector:
        entity:
          filter:
            integration: frigate
            domain: camera            
    notify:
      name: Notification Target
      selector:
        entity:
          multiple: true
          filter:
            integration: mobile_app
            domain: notify
    conditions:
      name: Notification Condition(s)
      default: []
      selector:
        condition:
    mqtt:
      name: MQTT Path
      default: 'frigate/reviews'
      selector:
        text: 
    review_type:
      name: Review Type
      selector:
        select:
          options:
            - label: Alerts and Detections
              value: all
            - label: Alerts
              value: alert
            - label: Detections
              value: detection

mode: queued

variables:
  camera_entity: !input camera
  camera_name: "{{ camera_entity | replace ('camera.', '')}}"
  mobile_devices: !input notify
  permitted_severity: !input review_type
      
triggers:
  - trigger: mqtt
    topic: !input mqtt

conditions:
  - condition: template
    value_template: "{{ trigger.payload_json.after.camera == camera_name }}"


actions:
  - variables:
      review_id: "{{ trigger.payload_json.after.id }}"
      update_type: "{{ trigger.payload_json.type }}"
      review_type: "{{ trigger.payload_json.after.severity }}"
      trigger_time: '{{trigger.payload_json["after"]["start_time"]|int}}'
  - condition: template
    value_template: >
           {% if permitted_severity == review_type %}
               true
           {% elif permitted_severity == 'all' %}
              true
           {% else %}
              false
           {% endif %}
  - repeat:
      for_each: "{{ mobile_devices }}"
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ update_type != 'end' }}"
              sequence:
                - action: "notify.mobile_app_{{ repeat.item | replace ('notify.', '')}}"
                  data:
                    title: Frigate
                    message: "{{ 'Camera ' + camera_name + ' has been triggered.' }}"
                    data:
                      image: "https://hass.arnie580.co.uk/api/frigate/notifications/{{ review_id }}/{{ camera_name }}/review_thumbnail.webp"
                      tag: "{{ review_id }}"
                      when: "{{ trigger_time }}"

            - conditions:
                - condition: template
                  value_template: "{{ update_type == 'end' }}"
              sequence:
                - delay:
                    seconds: 5
                - action: "notify.mobile_app_{{ repeat.item | replace ('notify.', '')}}"
                  data:
                    title: Frigate
                    message: "{{ 'Camera ' + camera_name + ' has been triggered.' }}"
                    data:
                      image: "https://hass.arnie580.co.uk/api/frigate/notifications/{{ review_id }}/review_preview.gif"
                      tag: "{{ review_id }}"
                      when: "{{ trigger_time }}"
