blueprint:
  name: Medication Reminder
  description: Automation that sends notifications at set times as a reminder to take medication. There are options to name the medication, person, and dosage. The notification will not be cleared until it is confirmed the dose has been taken.
  domain: automation
  input:
    medication_name:
      name: Medication
      selector:
        text:
    medication_dose:
      name: Dose
      selector:
        text:
    medication_patient:
      name: Patient
      selector: 
        text:
    medication_time:
      name: Time Due
      selector:
        text:
          multiple: true
          multiline: true
          type: time
    notification_entity:
      name: Notification Entity
      selector:
        device:
          multiple: true
          entity:
            integration: mobile_app


variables:
  medication_name: !input medication_name
  medication_dose: !input medication_dose
  medication_patient: !input medication_patient
  
triggers:
  - trigger: time
    at: !input medication_time

actions: 
  - repeat:
      for_each:
        !input notification_entity
      sequence:
        - action: "notify.mobile_app_{{device_name(repeat.item)|lower|replace(" ","_")}}"
          data:
            title: Medication Reminder
            message: "{{ medication_patient + ' is due to take ' + medication_name + ' (' + medication_dose + ')' }}"
