# Triggers:
# Schedule @
# Presence @
# Windows/Doors
# Temp Change @

# Inputs:
# Schedule @
# TRV @
# TRV Temp Setting @
# Night Temp @
# Day Temp @ 
# Windows/Doors @
# Temp Sensor @

# Actions:
# Turn off when window opens
# Turn on when window closes

# Turn off when going out
# Turn on when coming home

# Day temp when schedule turns on
# Night temp when schedule turns off

# Set the temperature when the sensor changes

blueprint:
  name: TRV Heating
  description: Manages Sonoff smart thermostatic radiator valves on a room by room basis including presence, open window, schedules, and external temperature sensors.
  domain: automation
  input:
    trv:
      name: Thermostatic Valve
      selector:
        entity:
          filter:
            domain: climate
    trv_temp_input:
      name: TRV Temperature Input
      selector:
        entity:
          filter:
            domain: number
    external_temp:
      name: External Temperature Sensor
      selector:
        entity:
          filter:
            domain: sensor
            device_class: temperature
    schedule:
      name: Heating Schedule
      selector:
        entity:
          filter:
            domain: schedule
    openings:
      name: Window and Door Sensors
      description: Multiple sensors must be added to a group
      selector:
        entity:
          filter:
            domain: 
              - binary_sensor
              - group
            device_class:
              - door
              - window
    day_temp:
      name: Day Temperature
      selector:
        entity:
          filter:
            domain: input_number
    night_temp:
      name: Night Temperature
      selector:
        entity:
          filter:
            domain: input_number
    presence:
      name: Presence Detection
      selector:
        entity:
          filter:
            domain:
              - group
              - device_tracker
    
triggers:
  - trigger: state
    entity_id: !input schedule
    id: schedule
  - trigger: state
    entity_id: !input presence
    id: presence
  - trigger:  state
    entity_id: !input external_temp
    id: temperature
  - trigger: state
    entity_id: !input openings
    id: openings

actions:
  choose:
  ### Temperature Change ###
    conditions:
      - condition: template
        value_template: '{{ trigger.id == "temperature" }}'
    sequence:
      - action: number.set_value
        data:
          entity_id: !input trv_temp_input
          value: !input external_temp
  ### Schedule ###
  ### Open Window ###
  ### Presence ###
