# Triggers:
# Schedule @
# Windows/Doors @
# Temp Change @

# Inputs:
# Schedule @
# TRV @
# TRV Temp Setting @
# Night Temp @
# Day Temp @ 
# Windows/Doors @
# Temp Sensor @

# Actions:
# Turn off when window opens
# Turn on when window closes


# Day temp when schedule turns on
# Night temp when schedule turns off

# Set the temperature when the sensor changes

blueprint:
  name: TRV Heating
  description: Manages Sonoff smart thermostatic radiator valves on a room by room basis including presence, open window, schedules, and external temperature sensors.
  domain: automation
  input:
    trv:
      name: Thermostatic Valve
      selector:
        entity:
          filter:
            domain: climate
    trv_temp_input:
      name: TRV Temperature Input
      selector:
        entity:
          filter:
            domain: number
    external_temp:
      name: External Temperature Sensor
      selector:
        entity:
          filter:
            domain: sensor
            device_class: temperature
    schedule:
      name: Heating Schedule
      selector:
        entity:
          filter:
            domain: schedule
    openings:
      name: Window and Door Sensors
      description: Multiple sensors must be added to a group
      selector:
        entity:
          filter:
            domain: 
              - binary_sensor
              - group
    day_temp:
      name: Day Temperature
      selector:
        entity:
          filter:
            domain: input_number
    night_temp:
      name: Night Temperature
      selector:
        entity:
          filter:
            domain: input_number
variables:
  external_temp: !input external_temp
  day_temp: !input day_temp
  night_temp: !input night_temp
triggers:
  - trigger: state
    entity_id: !input schedule
    id: schedule
  - trigger:  state
    entity_id: !input external_temp
    id: temperature
  - trigger: state
    entity_id: !input openings
    id: openings
    for:
      seconds: 30
actions:
  - choose:

  
  ### Temperature Change ###
      - conditions:
          - condition: template
            value_template: '{{ trigger.id == "temperature" }}'
        sequence:
          - action: number.set_value
            target:
              entity_id: !input trv_temp_input
            data:
              value: "{{ states(external_temp) | float }}"

              
  ### Schedule ###
      - conditions:
          - condition: template
            value_template: '{{ trigger.id == "schedule" }}'
          - condition: state
            entity_id: !input openings
            state: 'off'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input schedule
                    state: 'on'
                sequence:
                  - action: climate.set_temperature
                    target: 
                      entity_id: !input trv
                    data:
                      temperature: '{{ states(day_temp) | float }}'
              - conditions:
                  - condition: state
                    entity_id: !input schedule
                    state: 'off'
                sequence:
                  - action: climate.set_temperature
                    target: 
                      entity_id: !input trv
                    data:
                      temperature: '{{ states(night_temp) | float }}'

                      
  ### Open Window ###
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'openings' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input openings
                    state: 'on'
                sequence:
                  - action: climate.set_temperature
                    target:
                      entity_id: !input trv
                    data:
                      temperature: 7
              - conditions:
                  - condition: state
                    entity_id: !input openings
                    state: 'off'
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: !input schedule
                            state: 'on'
                        sequence:
                          - action: climate.set_temperature
                            target: 
                              entity_id: !input trv
                            data:
                              temperature: '{{ states(day_temp) | float }}'
                      - conditions:
                          - condition: state
                            entity_id: !input schedule
                            state: 'off'
                        sequence:
                          - action: climate.set_temperature
                            target: 
                              entity_id: !input trv
                            data:
                              temperature: '{{ states(night_temp) | float }}'
