blueprint:
  name: Simple Light Control with Configurable Delay
  description: Turn on a light with a binary sensor and keep it on for a user-configurable amount of time. If the sensor is triggered again, the timer restarts.
  domain: automation
  input:
    binary_sensor_entity:
      name: Binary Sensor
      description: The binary sensor that triggers the light.
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Light
      description: The light to control.
      selector:
        entity:
          domain: light
    delay_time:
      name: Delay Time
      description: The amount of time the light stays on after being triggered.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

trigger:
  platform: state
  entity_id: !input binary_sensor_entity
  to: 'on'

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
  - wait_for_trigger:
      - platform: state
        entity_id: !input binary_sensor_entity
        to: 'off'
  - delay: 
      minutes: !input delay_time
  - service: light.turn_off
    target:
      entity_id: !input light_entity

mode: restart
